# Generated by Django 3.0.6 on 2020-06-10 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Email_verification',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=1024)),
                ('expiry', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ORMProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.TextField()),
                ('technology', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ORMUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('college_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('1', 'Student'), ('2', 'Admin'), ('3', 'Internal team'), ('4', 'Teacher'), ('5', 'Others')], default='1', max_length=20)),
                ('userimage', models.ImageField(upload_to=None)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30, null=True)),
                ('disable_account', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True)),
                ('login_count', models.PositiveIntegerField(blank=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='useraccount.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.IntegerField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_me', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.ORMProject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='useraccount.ORMUser')),
            ],
        ),
        migrations.AddField(
            model_name='ormuser',
            name='skill',
            field=models.ManyToManyField(to='useraccount.Skill'),
        ),
    ]
